baseURL: "https://datavizf18.classes.andrewheiss.com/"
languageCode: en-us
title: Data visualization
theme: "ath-tufte-hugo_18-19"
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: true
menu:
  main:
    - name: Syllabus
      url: /syllabus/
      weight: 1
    - name: Assignments
      url: /assignments/
      weight: 3
    - name: Schedule
      url: /schedule/
      weight: 2
    - name: Reference
      url: /reference/
      weight: 4
    - name: RStudio.cloud
      url: "https://rstudio.cloud"
      weight: 5
    - name: Class Slack
      url: "https://byudatavizf2018.slack.com"
      weight: 6
# Disable taxonomies
taxonomies:
  tag: ""
  group: ""
  category: ""
params:
  author: Andrew Heiss
  thumbnail: /images/dataviz_meta.png
  instructor: 
    name: Dr. Andrew Heiss
    email: andrew_heiss@byu.edu
    url: "https://www.andrewheiss.com"
    twitter: andrewheiss
    github: andrewheiss
    office: 639 TNRB
  course:
    number: MPA 635
    semester: Fall 2018
    days: "Tuesdays"
    time: "3:30–4:45 PM"
    location: "W110 TNRB"
    twitter: andrewheiss
    dates: "September 4–December 11, 2018"
    github: "andrewheiss/datavizf18.classes.andrewheiss.com"
    slack: "https://byudatavizf2018.slack.com"
    copyrightYear: "2018"
    contactDetails: >-
      Office hours: [Sign up here.](https://calendly.com/andrewheiss/meeting/)<br><br>E-mail is the best way to get in contact with me—I will respond to all course-related e-mails within 24 hours (*really*).
  university: 
    name: Brigham Young University
    url: "https://www.byu.edu"
  school:
    name: Romney Institute of Public Service and Ethics
    url: "https://marriottschool.byu.edu/mpa/"
  description: "Communicate science and statistics with beautiful graphics"
  primaryColor: "#DA5B69"
  secondaryColor: "#F9983E"
  credits: >-
    Hex icon by Andrew Heiss, with a stylized version of [Hans Rosling's health+wealth plot](https://www.youtube.com/watch?v=jbkSRLYSojo).<br>Color scheme adapted from the [viridis plasma map](https://github.com/sjmgarnier/viridis).
  logo:
    url: /images/dataviz_hires.png
    alt: Data visualization
  meta:
    twitterSite: "@andrewheiss"
    twitterCreator: "@andrewheiss"
    fbAuthor: "https://www.facebook.com/andrewheiss"
