---
title: "Code-through"
date: "2018-12-07"
due_date: "2018-12-07"
due_time: "11:59 PM"
editor_options: 
  chunk_output_type: console
---

<span class="newthought">The objectives of this class include</span> "Share data and graphics in open forums" and "Be curious and confident in consuming and producing data." To help you with this, you will write a short code-through tutorial of some data visualization principle, technique, or example.

One of the reasons R is so popular is because the R community is exceptionally generous and open and sharing.^[So are Python and other modern open source languages too.] The internet is full of tutorials and code-throughs where people explain how to do something interesting with R.

You will complete this assignment on your own, but you can get help from others (but you can't all write about the same topic).


# Instructions

Here's what you need to do:

1. **Decide** what data visualization concept you want to demonstrate. Perhaps you want to compare pie charts with waffle charts, or show why truncating the y-axis is okay (or not), or demonstrate how to use some cool `ggplot` package like `ggparliament`, or show how to use different `theme()` options to make plots CRAPier, or show why map projections make a difference when plotting geographic data, or how to explore some cool dataset with graphics. This is up to you!

2. **Write** a tutorial that walks a reader through a demonstration of this concept. Your mini projects and problem sets have been focused on the final product. In this assignment, here the focus is didactic. Show intermediate steps, explain why you add additional layers or make intermediate summary data frames, etc. The reader should learn something new from this tutorial.

    There's no word count here, but there should be several steps and examples of the concept you're demonstrating.

    You should write this in R Markdown, since that allows you to mix prose and code.

    Your demonstration **must be reproducible**. Either use built-in datasets like `iris` or `mtcars`, or point the reader to a CSV file from the internet and incorporate `read_csv()` into your code-through.

3. **Knit** the final version of your tutorial as a PDF, Word file, or HTML file.

4. **Upload** the knitted document to Learning Suite. 

    If you're feeling especially brave, post the HTML version of your document to some public website ([Medium](https://medium.com/), a personal blog, etc.), tell me, and I'll promote it in the #rstats community on Twitter. You'll probably get super rich and famous if you do this.

I will grade this using a check system.


# Examples

The code examples I include on each week's class page are a good example of didactic tutorials. In addition, the [R-Weekly e-mail newsletter](https://rweekly.org/) includes dozens of these kinds of tutorials every week, and [Mara Averick](https://twitter.com/dataandme) (chief tidyverse advocate at RStudio) regularly tweets out links to different posts as well. Here are some others examples to give you a jist of what you can do:^[{-} Yours won't be nearly as complicated as these, by the way. Nor do they need to be.]

- [The Greatest Twitter Scheme of All Time?](https://www.garrickadenbuie.com/blog/2018/08/24/greatest-twitter-scheme/)
- [Mapping Fall Foliage with sf](https://rud.is/b/2017/09/18/mapping-fall-foliage-with-sf/)
- [Drawing beautiful maps programmatically with R, sf and ggplot2](https://www.r-spatial.org//r/2018/10/25/ggplot2-sf.html)
- [Exploring Minard's 1812 plot with ggplot2](https://www.andrewheiss.com/blog/2017/08/10/exploring-minards-1812-plot-with-ggplot2/)
- [Animations in R](https://www.infoworld.com/video/89987/r-tip-animations-in-r)
- [Drone sightings in the US, visualized](https://www.andrewheiss.com/blog/2016/04/03/drone-sightings-in-the-us-visualized/)
- [Quickly play with Polity IV and OECD data (and see the danger of US democracy)](https://www.andrewheiss.com/blog/2017/08/26/quickly-play-with-polity-iv-and-oecd-data-and-see-the-danger-of-us-democracy/)
